"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "sw"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Language dictionary
const translations = {
  en: {
    phone_placeholder: "+255 XXX XXX XXX",
    enter_nida_number: "Enter NIDA number",
    tenant: "Tenant",
    generate_otp_for_tenant: "Generate OTP for tenant",
    generated: "Generated",
    generate: "Generate",
    otp_sent_info: "This OTP will be sent to the tenant for account setup",
    adding: "Adding...",
    draft: "Draft",
    lease_end: "Lease End",
    status: "Status",
    registered: "Registered",
    time_remaining: "Time Remaining",
    lease_expired: "Lease expired",
    days_left: "days left",
    percent: "%",
    call: "Call",
    view_profile: "View Profile",
    monthly_payment_info: "This amount will be set as the tenant's monthly payment",
    lease_start: "Lease Start Date",
    lease_period: "Lease Period (months)",
    select_period: "Select period",
    months: "months",
    total_tenants: "Total Tenants",
    active_leases: "Active Leases",
    paid_this_month: "Paid This Month",
    overdue: "Overdue",
    total: "Total",
    approval_rate: "Approval Rate",
    avg_response: "Avg. Response",
    approve: "Approve",
    reject: "Reject",
    send_lease: "Send Lease",
    review: "Review",
    details: "Details",
    not_available: "N/A",
    shared: "Shared",
    not_shared: "Not Shared",
    generate_lease_agreement: "Generate Lease Agreement",
    error_move_to_review: "Error moving to review. Please try again.",
    rejection_reason: "Rejection Reason",
    tenant_applications_title: "Tenant Applications",
    review_and_manage_rental_applications: "Review and manage rental applications",
    search_applications_placeholder: "Search by name, property or email...",
    pending: "Pending",
    in_review: "In Review",
    approved: "Approved",
    rejected: "Rejected",
    rented: "Rented",
    properties_title: "Properties",
    manage_your_property_portfolio: "Manage your property portfolio",
    search_properties_placeholder: "Search properties...",
    avg_rent: "Avg. Rent",
    no_properties_yet: "No properties yet",
    add_first_property_to_get_started: "Add your first property to get started",
    bed: "bed",
    bath: "bath",
    add_new_property: "Add New Property",
    list_a_new_property_for_rent: "List a new property for rent",
    basic_information: "Basic Information",
    provide_main_details_about_property: "Provide the main details about your property",
    property_title: "Property Title",
    eg_modern_downtown_apartment: "e.g., Modern Downtown Apartment",
    describe_your_property: "Describe your property...",
    location: "Location",
    where_is_your_property_located: "Where is your property located?",
    street_address: "Street Address",
    eg_123_main_street: "123 Main Street",
    city: "City",
    select_city: "Select city",
    region: "Region",
    eg_kinondoni: "e.g., Kinondoni",
    postal_code: "Postal Code",
    optional: "Optional",
    property_details: "Property Details",
    specifications_and_features: "Specifications and features",
    eg_2: "2",
    eg_1200: "1200",
    public_toilet_available: "Public Toilet Available",
    electricity_bill_type: "Electricity Bill Type",
    select_type: "Select type",
    individual_meter: "Individual Meter",
    shared_main_meter: "Shared/Main Meter",
    electricity_bill_amount: "Electricity Bill Amount (Tsh/month)",
    eg_30000: "e.g. 30000",
    water_bill_amount: "Water Bill Amount (Tsh/month)",
    eg_20000: "e.g. 20000",
    submeters_installed: "Submeters Installed",
    monthly_rent: "Monthly Rent",
    eg_500000: "500000",
    security_deposit: "Security Deposit",
    amenities: "Amenities",
    select_all_that_apply: "Select all that apply",
    photos: "Photos",
    add_photos_of_your_property: "Add photos of your property",
    upload_photos: "Upload Photos",
    cancel: "Cancel",
    parking: "Parking",
    gym: "Gym",
    pool: "Pool",
    dishwasher: "Dishwasher",
    ac: "AC",
    heating: "Heating",
    pet_friendly: "Pet Friendly",
    balcony: "Balcony",
    yard: "Yard",
    furnished: "Furnished",
    utilities_included: "Utilities Included",
    no_upcoming_payments: "No upcoming payments",
    show_less: "Show Less",
    recent_applications: "Recent Applications",
    new_tenant_applications_waiting_for_review: "New tenant applications waiting for review",
    upcoming_payments: "Upcoming Payments",
    rent_payments_due_soon: "Rent payments due soon",
    view_all: "View All",
    monthly_revenue: "Monthly Revenue",
    compared_to_last_month: "Compared to last month",
    pending_applications: "Pending Applications",
    require_your_review: "Require your review",
    reports: "Reports",
    lease_contract_template: "Lease / Contract Template",
    manage_lease_template_for_tenants: "Manage your lease template for tenants",
    open: "Open",
    applications: "Applications",
    finance: "Finance",
    expenses: "Expenses",
    vaults: "Vaults",
    payments: "Payments",
    send_lease: "Send Lease",
    property_occupied: "Property Occupied",
    property_occupied_desc: "This property is already rented/occupied.\nYou cannot rent this property.",
    close: "Close",
    manage_tenants: "Manage your tenants",
    add_tenant: "Add Tenant",
    add_new_tenant: "Add New Tenant",
    first_name: "First Name",
    last_name: "Last Name",
    dashboard: "Dashboard",
    property_management: "Property Management",
    verify_account: "Verify Account",
    verifying_account_tooltip: "Verifying your account increases trust and unlocks all features.",
    notifications: "Notifications",
    new: "new",
    no_notifications_yet: "No notifications yet",
    welcome_back_dashboard: "Welcome back",
    dashboard_subtitle: "Here's what's happening with your properties today.",
    total_properties: "Total Properties",
    across_all_locations: "Across all locations",
    healthy: "Healthy",
    moderate: "Moderate",
    low: "Low",
    occupancy_rate: "Occupancy Rate",
    welcome_back: "Welcome Back",
    sign_in_to_continue: "Sign in to your account to continue",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    signing_in: "Signing in...",
    enter_email_password: "Enter your email and password to access your dashboard",
    email_placeholder: "you@example.com",
    password_placeholder: "••••••••",
    forgot_password: "Forgot password?",
    dont_have_account: "Don't have an account?",
    for_every_role: "For Every Role",
    built_for_everyone: "Built for Everyone in Real Estate",
    three_powerful_dashboards: "Three powerful dashboards tailored to your specific needs",
    landlords_desc: "List properties, screen tenants with credit checks, manage leases, and collect rent payments all in one platform.",
    property_portfolio_management: "Property portfolio management",
    automated_tenant_screening: "Automated tenant screening",
    rent_collection_tracking: "Rent collection & tracking",
    tenants_desc: "Search properties, build your rental profile with verified financials, apply instantly, and make payments online.",
    advanced_property_search: "Advanced property search",
    financial_profile_builder: "Financial profile builder",
    one_click_applications: "One-click applications",
    agents_desc: "Manage client relationships, facilitate deals, track commissions, and access verified tenant data for faster closings.",
    deal_pipeline_management: "Deal pipeline management",
    commission_tracking: "Commission tracking",
    client_verification_tools: "Client verification tools",
    learn_more: "Learn more",
    core_features: "Core Features",
    powerful_financial_verification: "Powerful Financial Verification",
    everything_you_need: "Everything you need to make secure, informed rental decisions",
    credit_score_integration: "Credit Score Integration",
    credit_score_integration_desc: "Real-time credit score checks from major bureaus. View detailed credit history and payment patterns.",
    document_verification: "Document Verification",
    document_verification_desc: "Secure upload and verification of pay stubs, bank statements, and employment letters with AI validation.",
    background_checks: "Background Checks",
    background_checks_desc: "Comprehensive background screening including criminal history, eviction records, and rental history.",
    income_verification: "Income Verification",
    income_verification_desc: "Automated income verification through payroll integration and bank statement analysis.",
    property_analytics: "Property Analytics",
    property_analytics_desc: "Market analysis, rental price suggestions, and occupancy forecasting powered by local market data.",
    api_for_lenders: "API for Lenders",
    api_for_lenders_desc: "RESTful API providing verified tenant financial data to banks and lending institutions.",
    getting_started: "Getting Started",
    how_it_works: "How It Works",
    get_started_in_minutes: "Get started in minutes with our streamlined process",
    create_your_profile: "Create Your Profile",
    create_your_profile_desc: "Sign up as a landlord, tenant, or agent. Complete your profile with relevant information and verification documents.",
    list_or_search_properties: "List or Search Properties",
    list_or_search_properties_desc: "Landlords list properties with photos and details. Tenants search and filter by location, price, and amenities. Agents manage both sides.",
    verify_financial_information: "Verify Financial Information",
    verify_financial_information_desc: "Tenants submit applications with automated credit checks and income verification. Landlords review verified data instantly.",
    close_the_deal: "Close the Deal",
    close_the_deal_desc: "Approve applications, sign digital leases, and start collecting rent. Agents earn commissions tracked automatically in the platform.",
    simple_transparent_pricing: "Simple, Transparent Pricing",
    choose_the_plan: "Choose the plan that fits your portfolio. Upgrade anytime as you grow.",
    free: "Free",
    up_to_3_units: "Up to 3 units",
    basic_property_management: "Basic property management",
    tenant_lease_tracking: "Tenant & lease tracking",
    basic_reporting: "Basic reporting",
    start_free: "Start Free",
    starter: "Starter",
    up_to_10_units: "Up to 10 units",
    payments_reminders: "Payments & reminders",
    reports_arrears_tracking: "Reports & arrears tracking",
    email_support: "Email support",
    start_starter: "Start Starter",
    professional: "Professional",
    up_to_50_units: "Up to 50 units",
    full_financial_dashboard_analytics: "Full Financial Dashboard & analytics",
    priority_support: "Priority support",
    advanced_exports: "Advanced exports",
    start_professional: "Start Professional",
    enterprise: "Enterprise",
    unlimited_units: "Unlimited units",
    api_access: "API access",
    dedicated_support: "Dedicated support",
    custom_integrations: "Custom integrations",
    contact_sales: "Contact Sales",
    rentsecure: "RentSecure",
    footer_tagline: "Complete property management with financial verification for the modern rental market.",
    product: "Product",
    api_documentation: "API Documentation",
    company: "Company",
    about_us: "About Us",
    contact: "Contact",
    careers: "Careers",
    legal: "Legal",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    security: "Security",
    all_rights_reserved: "All rights reserved.",
    clients: "Clients",
    manage_landlord_tenant_relationships: "Manage your landlord and tenant relationships",
    add_client: "Add Client",
    search_clients_placeholder: "Search clients...",
    filters: "Filters",
    total_clients: "Total Clients",
    landlords: "Landlords",
    active: "Active",
    credit_score: "Credit Score",
    budget_range: "Budget Range",
    active_deals: "Active Deals",
    deals: "deal(s)",
    client_since: "Client Since",
    call: "Call",
    view_profile: "View Profile",
    // Navigation
    dashboard: "Dashboard",
    properties: "Properties",
    applications: "Applications",
    tenants: "Tenants",
    payments: "Payments",
    search: "Search",
    favorites: "Favorites",
    profile: "Profile",
    settings: "Settings",
    clients: "Clients",
    deals: "Deals",
    commissions: "Commissions",
    logout: "Logout",

    // Home Page
    features: "Features",
    how_it_works: "How It Works",
    pricing: "Pricing",
    trusted_property_platform: "Trusted Property Platform",
    hero_title: "Complete Property Management with ",
    hero_title_highlight: "Financial Verification",
    hero_subtitle: "Connect landlords, tenants, and agents with real-time credit scoring, tenant screening, and secure financial verification. Make informed decisions faster.",
    start_free_trial: "Start Free Trial",
    see_how_it_works: "See How It Works",

    // Common
    welcome: "Welcome",
    back: "Back",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Full Name",
    phone: "Phone Number",
    loading: "Loading",
    save: "Save",
    arrears_aging_report: "Arrears Aging Report",
    outstanding_balances_by_age_bucket: "Outstanding balances by age bucket (FIFO allocated)",
    total_outstanding: "Total Outstanding",
    arrears_0_30_days: "0-30 Days",
    arrears_31_60_days: "31-60 Days",
    arrears_61_90_days: "61-90 Days",
    arrears_90_plus_days: "90+ Days",
    amount_due: "Amount Due",
    days_overdue: "Days Overdue",
    remind: "Remind",
    arrears_highest_risk_message: "Mary Kessy (105 days overdue, 500K TZS) is highest risk for write-off. Initiate formal escalation. Automated FIFO allocation ensures oldest debts are prioritized.",
    ledger_transactions: "Ledger Transactions",
    canonical_ledger_entries: "Canonical ledger entries from reconciled PSP payments",
    entries: "entries",
    date: "Date",
    psp: "PSP",
    method: "Method",
    amount: "Amount",
    fee: "Fee",
    match: "Match",
    efd: "EFD",
    actions: "Actions",
    contact: "Contact",
    property: "Property",
    tenants: "tenants",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    search_placeholder: "Search...",
    filter: "Filter",
    sort: "Sort",

    // Property
    property: "Property",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    squareFeet: "Square Feet",
    rent: "Rent",
    monthly_rent: "Monthly Rent",
    security_deposit: "Security Deposit",
    available_date: "Available Date",
    property_type: "Property Type",
    amenities: "Amenities",
    description: "Description",
    location: "Location",
    view_details: "View Details",
    per_month: "per month",

    // Status
    available: "Available",
    rented: "Rented",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    active: "Active",
    inactive: "Inactive",
    completed: "Completed",

    // Actions
    apply_now: "Apply Now",
    pay_now: "Pay Now",
    view_property: "View Property",
    add_property: "Add Property",
    contact: "Contact",

    // Pages
    landlord_dashboard: "Landlord Dashboard",
    tenant_dashboard: "Tenant Dashboard",
    agent_dashboard: "Agent Dashboard",
    property_flow_tanzania: "PROPERTY FLOW Tanzania",
  },
  sw: {
    vacant: "Tupu",
      no_rejected_applications: "No Rejected Applications",
      rejected_applications_empty_desc: "Rejected applications will appear here",
      per_month: "per month",
      quick_actions: "Quick Actions",
      quick_actions_subtitle: "Common tasks and shortcuts",
      no_rejected_applications: "Hakuna maombi yaliyokataliwa",
      rejected_applications_empty_desc: "Maombi yaliyokataliwa yataonekana hapa",
      settings_title: "Settings",
      per_month: "kwa mwezi",
      settings_subtitle: "Manage your account and preferences",
      settings_profile_title: "Profile Information",
      quick_actions: "Hatua za Haraka",
      quick_actions_subtitle: "Kazi za kawaida na njia za mkato",
      settings_profile_subtitle: "Update your personal details",
      save_changes: "Save Changes",
      settings_notifications_title: "Notifications",
      settings_notifications_subtitle: "Configure how you receive updates",
      settings_notifications_new_applications: "New Applications",
      settings_notifications_new_applications_desc: "Get notified when tenants apply",
      settings_notifications_payment_reminders: "Payment Reminders",
      settings_notifications_payment_reminders_desc: "Upcoming rent payment notifications",
      settings_notifications_maintenance_requests: "Maintenance Requests",
      settings_notifications_maintenance_requests_desc: "Tenant maintenance request alerts",
      settings_notifications_monthly_reports: "Monthly Reports",
      settings_notifications_monthly_reports_desc: "Monthly performance summary",
      save_notifications: "Save Notifications",
      settings_security_title: "Security",
      settings_security_subtitle: "Password and account security",
      settings_security_current_password: "Current Password",
      settings_security_new_password: "New Password",
      settings_security_confirm_new_password: "Confirm New Password",
      update_password: "Update Password",
      updating: "Updating...",
      settings_payment_title: "Payment Information",
      settings_payment_subtitle: "Where you receive rent payments",
      settings_payment_bank_name: "Bank Name",
      settings_payment_bank_name_placeholder: "e.g. CRDB Bank",
      settings_payment_account_number: "Account Number",
      settings_payment_account_number_placeholder: "Enter account number",
      settings_payment_account_holder_name: "Account Holder Name",
      settings_payment_account_holder_name_placeholder: "Enter account holder name",
      settings_payment_mobile_money: "Mobile Money Number (Optional)",
      settings_payment_mobile_money_placeholder: "+255 7XX XXX XXX",
      save_payment_info: "Save Payment Info",
      saving: "Saving...",
      vault_access_title: "Vault Access",
      vault_access_subtitle: "Enter your account password to access your vault documents.",
      vault_password_placeholder: "Password",
      settings_title: "Mipangilio",
      settings_subtitle: "Simamia akaunti yako na mapendeleo",
      settings_profile_title: "Taarifa za Wasifu",
      settings_profile_subtitle: "Sasisha taarifa zako binafsi",
      save_changes: "Hifadhi Mabadiliko",
      settings_notifications_title: "Arifa",
      settings_notifications_subtitle: "Sanidi jinsi unavyopokea taarifa",
      settings_notifications_new_applications: "Maombi Mapya",
      settings_notifications_new_applications_desc: "Pata arifa wakati wapangaji wanatuma maombi",
      settings_notifications_payment_reminders: "Arifa za Malipo",
      settings_notifications_payment_reminders_desc: "Arifa za malipo ya kodi yanayokuja",
      settings_notifications_maintenance_requests: "Maombi ya Matengenezo",
      settings_notifications_maintenance_requests_desc: "Arifa za maombi ya matengenezo kutoka kwa wapangaji",
      settings_notifications_monthly_reports: "Ripoti za Mwezi",
      settings_notifications_monthly_reports_desc: "Muhtasari wa utendaji wa mwezi",
      save_notifications: "Hifadhi Arifa",
      settings_security_title: "Usalama",
      settings_security_subtitle: "Nenosiri na usalama wa akaunti",
      settings_security_current_password: "Nenosiri la Sasa",
      settings_security_new_password: "Nenosiri Mpya",
      settings_security_confirm_new_password: "Thibitisha Nenosiri Mpya",
      update_password: "Sasisha Nenosiri",
      updating: "Inasasisha...",
      settings_payment_title: "Taarifa za Malipo",
      settings_payment_subtitle: "Mahali unapopokea malipo ya kodi",
      settings_payment_bank_name: "Jina la Benki",
      settings_payment_bank_name_placeholder: "mf. CRDB Bank",
      settings_payment_account_number: "Namba ya Akaunti",
      settings_payment_account_number_placeholder: "Ingiza namba ya akaunti",
      settings_payment_account_holder_name: "Jina la Mmiliki wa Akaunti",
      settings_payment_account_holder_name_placeholder: "Ingiza jina la mmiliki wa akaunti",
      settings_payment_mobile_money: "Namba ya Simu ya Malipo (Hiari)",
      settings_payment_mobile_money_placeholder: "+255 7XX XXX XXX",
      save_payment_info: "Hifadhi Taarifa za Malipo",
      saving: "Inahifadhi...",
      vault_enter_button: "Enter Vault",
      vault_documents_title: "Document Vault",
      vault_documents_subtitle: "Securely store and manage all your important landlord documents in one place.",
      vault_upload_title: "Upload New Document",
      vault_upload_dragdrop: "Click to browse or drag and drop",
      vault_upload_fileinfo: "Max file size: 10MB • Supported: PDF, JPG, PNG, DOC, DOCX",
      vault_select_file_button: "Select File",
      vault_document_type_label: "Document Type",
      vault_document_type_placeholder: "Select document type",
      vault_document_type_lease: "Lease Agreement",
      vault_document_type_id: "Tenant ID",
      vault_document_type_contract: "Contract",
      vault_document_type_invoice: "Invoice",
      vault_document_type_receipt: "Receipt",
      vault_document_type_other: "Other",
      vault_uploading: "Uploading...",
      vault_upload_button: "Upload Document",
      vault_documents_list_title: "Your Documents",
      vault_refresh_button: "Refresh",
      vault_no_documents_title: "No documents yet",
      vault_no_documents_subtitle: "Upload your first document to get started",
      payments_title: "Payments",
      payments_subtitle: "Track rent payments and financial transactions",
      export_report_button: "Export Report",
      vault_access_title: "Ufikiaji wa Vault",
      vault_access_subtitle: "Weka nenosiri la akaunti yako ili kufikia nyaraka zako za vault.",
      vault_password_placeholder: "Nenosiri",
      vault_enter_button: "Ingia Vault",
      vault_documents_title: "Vault ya Nyaraka",
      vault_documents_subtitle: "Hifadhi na simamia nyaraka zako zote muhimu za mmiliki wa mali mahali pamoja kwa usalama.",
      vault_upload_title: "Pakia Nyaraka Mpya",
      vault_upload_dragdrop: "Bonyeza kuchagua au buruta na dondosha",
      vault_upload_fileinfo: "Ukubwa wa faili max: 10MB • Zinazosaidiwa: PDF, JPG, PNG, DOC, DOCX",
      vault_select_file_button: "Chagua Faili",
      vault_document_type_label: "Aina ya Nyaraka",
      vault_document_type_placeholder: "Chagua aina ya nyaraka",
      vault_document_type_lease: "Mkataba wa Kukodisha",
      vault_document_type_id: "Kitambulisho cha Mpangaji",
      vault_document_type_contract: "Mkataba",
      vault_document_type_invoice: "Ankara",
      vault_document_type_receipt: "Risiti",
      vault_document_type_other: "Nyingine",
      vault_uploading: "Inapakia...",
      vault_upload_button: "Pakia Nyaraka",
      vault_documents_list_title: "Nyaraka Zako",
      vault_refresh_button: "Pakia Upya",
      vault_no_documents_title: "Hakuna nyaraka bado",
      vault_no_documents_subtitle: "Pakia nyaraka yako ya kwanza kuanza",
      search_payments_placeholder: "Search payments...",
      filters_button: "Filters",
      total_received_stat: "Total Received",
      this_month_stat: "This month",
      pending_stat: "Pending",
      awaiting_payment_stat: "Awaiting payment",
      overdue_stat: "Overdue",
      requires_attention_stat: "Requires attention",
      transactions_stat: "Transactions",
      total_records_stat: "Total records",
      all_tab: "All",
      pending_tab: "Pending",
      completed_tab: "Completed",
      overdue_tab: "Overdue",
      recent_payments_title: "Recent Payments",
      recent_payments_subtitle: "All payment transactions for your properties",
      no_payments_found: "No payments found",
      payments_appear_info: "Payments will appear here when tenants make them",
      receipt_button: "Receipt",
      reminder_button: "Reminder",
      pending_payments_title: "Pending Payments",
      pending_payments_subtitle: "Payments awaiting tenant action",
      no_pending_payments: "No pending payments",
      completed_payments_title: "Completed Payments",
      completed_payments_subtitle: "Successfully received payments",
      no_completed_payments: "No completed payments",
      overdue_payments_title: "Overdue Payments",
      overdue_payments_subtitle: "Payments past their due date",
      no_overdue_payments: "No overdue payments",
      send_notice_button: "Send Notice",
      expense_select_category_placeholder: "Select category",
      expense_select_property_placeholder: "Select property",
      expense_amount_placeholder: "e.g. 450000",
      payments_title: "Malipo",
      payments_subtitle: "Fuatilia malipo ya kodi na miamala ya kifedha",
      export_report_button: "Hamisha Ripoti",
      search_payments_placeholder: "Tafuta malipo...",
      filters_button: "Vichujio",
      total_received_stat: "Jumla Iliyopokelewa",
      this_month_stat: "Mwezi huu",
      pending_stat: "Inasubiri",
      awaiting_payment_stat: "Inasubiri malipo",
      overdue_stat: "Imekawia",
      requires_attention_stat: "Inahitaji uangalizi",
      transactions_stat: "Miamala",
      total_records_stat: "Rekodi zote",
      all_tab: "Zote",
      pending_tab: "Inasubiri",
      completed_tab: "Imekamilika",
      overdue_tab: "Imekawia",
      recent_payments_title: "Malipo ya Hivi Karibuni",
      recent_payments_subtitle: "Miamala yote ya malipo kwa mali zako",
      no_payments_found: "Hakuna malipo yaliyopatikana",
      payments_appear_info: "Malipo yataonekana hapa pindi wapangaji watakapolipa",
      receipt_button: "Risiti",
      reminder_button: "Kumbusho",
      pending_payments_title: "Malipo Yanayosubiri",
      pending_payments_subtitle: "Malipo yanayosubiri hatua ya mpangaji",
      no_pending_payments: "Hakuna malipo yanayosubiri",
      completed_payments_title: "Malipo Yaliyokamilika",
      completed_payments_subtitle: "Malipo yaliyopokelewa kwa mafanikio",
      no_completed_payments: "Hakuna malipo yaliyokamilika",
      overdue_payments_title: "Malipo Yaliyokawia",
      overdue_payments_subtitle: "Malipo yaliyopita tarehe ya mwisho",
      no_overdue_payments: "Hakuna malipo yaliyokawia",
      send_notice_button: "Tuma Notisi",
      expense_date_placeholder: "dd/mm/yyyy",
      expense_management_title: "Expense Management",
      expense_management_subtitle: "Track, analyze, and manage all property expenses",
      record_new_expense: "Record New Expense",
      expense_select_category_placeholder: "Chagua kategoria",
      expense_select_property_placeholder: "Chagua mali",
      expense_amount_placeholder: "mf. 450000",
      expense_date_placeholder: "dd/mm/yyyy",
      expense_form_description: "Fill in any details about the expense — all fields are free text",
      expense_category_label: "Type / Category",
      expense_property_label: "Property",
      expense_amount_label: "Amount (TZS)",
      expense_date_label: "Date",
      expense_description_label: "Description",
      expense_description_placeholder: "Describe this expense...",
      save_expense_button: "Save Expense",
      by_category_chart_title: "By Category",
      by_category_chart_subtitle: "Category spending over time",
      monthly_trends_chart_title: "Monthly Trends",
      monthly_trends_chart_subtitle: "Expense trends over the last 6 months",
      monthly_trends_insight: "February expenses {direction} by {change}% vs January. Maintenance remains the largest cost driver at {amount} TZS.",
      all_expenses_table_title: "All Expenses",
      expense_table_date: "Date",
      expense_table_category: "Category",
      expense_table_property: "Property",
      expense_table_amount: "Amount",
      expense_table_notes: "Notes",
      manage_plan: "Manage Plan",
      no_property_performance_data: "No property performance data available.",
      all_properties_positive_noi: "All properties have positive NOI.",
      expense_management_title: "Usimamizi wa Matumizi",
      expense_management_subtitle: "Fuatilia, changanua, na simamia matumizi ya mali",
      record_new_expense: "Rekodi Matumizi Mapya",
      expense_form_description: "Jaza maelezo yoyote kuhusu matumizi — sehemu zote ni maandishi huru",
      expense_category_label: "Aina / Kategoria",
      expense_property_label: "Mali",
      expense_amount_label: "Kiasi (TZS)",
      expense_date_label: "Tarehe",
      expense_description_label: "Maelezo",
      expense_description_placeholder: "Elezea matumizi haya...",
      save_expense_button: "Hifadhi Matumizi",
      by_category_chart_title: "Kwa Kategoria",
      by_category_chart_subtitle: "Matumizi kwa kategoria kwa muda",
      monthly_trends_chart_title: "Mwelekeo wa Mwezi",
      monthly_trends_chart_subtitle: "Mwelekeo wa matumizi kwa miezi 6 iliyopita",
      monthly_trends_insight: "Matumizi ya Februari {direction} kwa {change}% dhidi ya Januari. Matengenezo bado ni gharama kubwa zaidi kwa {amount} TZS.",
      all_expenses_table_title: "Matumizi Yote",
      expense_table_date: "Tarehe",
      expense_table_category: "Kategoria",
      expense_table_property: "Mali",
      expense_table_amount: "Kiasi",
      expense_table_notes: "Maelezo",
      prioritize_filling: "Prioritize filling {properties} (vacant, negative NOI).",
      manage_plan: "Simamia Mpango",
      escalate_collection: "Escalate collection on {properties} (occupied, non-paying tenant).",
      default_negative_noi_message: "Garden House C2 and Hill Top E2 have negative NOI — vacant unit and non-paying tenant respectively. Prioritize filling C2 and escalating collection on E2.",
      privacy_notice_trustscore_title: "Privacy Notice: TrustScore",
      privacy_notice_trustscore_body: "Individual tenant TrustScores are not displayed in the Financial Dashboard. Tenant credit data follows a consent-based pull model (similar to bank/credit bureau practices) and is only accessible during the application process in the Marketplace (Layer 2). For portfolio-level insight, aggregated anonymized metrics such as average TrustScore may be enabled separately with appropriate privacy safeguards.",
      reports_export_actions_title: "Reports & Export Actions",
      reports_export_actions_subtitle: "Generate reports, export data, and send reminders",
      download_rent_roll_pdf: "Download Rent Roll (PDF)",
      export_pl_excel: "Export P&L (Excel)",
      efd_compliance_report: "EFD Compliance Report",
      send_arrears_reminders: "Send Arrears Reminders",
      enterprise_plan_title: "Enterprise Plan — TZS 150,000+/month",
      enterprise_plan_features: "Unlimited units, full analytics, API access, dedicated support, audit logging",
      full_dashboard: "Full Dashboard",
      api_access: "API Access",
      priority_support: "Priority Support",
    occupied: "Imejazwa",
    property_performance: "Utendaji wa Mali",
    arrears_aging: "Umri wa Madeni",
      no_property_performance_data: "Hakuna data ya utendaji wa mali.",
      all_properties_positive_noi: "Mali zote zina NOI chanya.",
      prioritize_filling: "Panga kujaza {properties} (imebaki tupu, NOI hasi).",
      escalate_collection: "Ongeza ukusanyaji kwa {properties} (imejazwa, mpangaji asiyelipa).",
      default_negative_noi_message: "Garden House C2 na Hill Top E2 zina NOI hasi — moja tupu na nyingine mpangaji asiyelipa. Panga kujaza C2 na kuongeza ukusanyaji kwa E2.",
      privacy_notice_trustscore_title: "Notisi ya Faragha: TrustScore",
      privacy_notice_trustscore_body: "TrustScore za wapangaji binafsi hazionyeshwi kwenye Dashibodi ya Fedha. Data ya mikopo ya mpangaji inapatikana tu kwa idhini wakati wa mchakato wa maombi kwenye Marketplace (Layer 2). Kwa ufahamu wa kiwango cha portfolio, vipimo vilivyofupishwa vinaweza kuwezeshwa na ulinzi wa faragha unaofaa.",
      reports_export_actions_title: "Ripoti & Vitendo vya Uhamishaji",
      reports_export_actions_subtitle: "Tengeneza ripoti, hamisha data, na tuma vikumbusho",
      download_rent_roll_pdf: "Pakua Rent Roll (PDF)",
      export_pl_excel: "Hamisha P&L (Excel)",
      efd_compliance_report: "Ripoti ya Uzingatiaji wa EFD",
      send_arrears_reminders: "Tuma Vikumbusho vya Madeni",
      enterprise_plan_title: "Mpango wa Enterprise — TZS 150,000+/mwezi",
      enterprise_plan_features: "Vitengo visivyo na kikomo, uchambuzi kamili, ufikiaji wa API, msaada maalum, ufuatiliaji wa ukaguzi",
      full_dashboard: "Dashibodi Kamili",
      api_access: "Ufikiaji wa API",
      priority_support: "Msaada wa Kipaumbele",
    ledger_transactions: "Muamala wa Ledger",
    property_performance_drilldown: "Uchambuzi wa Utendaji wa Mali",
    financial_breakdown_by_property_and_unit: "Uchanganuzi wa kifedha kwa mali na kitengo",
    cash_flow_analysis: "Cash Flow Analysis",
    revenue_vs_expenses_monthly: "Revenue vs Expenses (Monthly)",
    payment_status: "Payment Status",
    distribution_of_payment_timeliness: "Distribution of payment timeliness",
    on_time: "On Time",
    late: "Late",
    partial: "Partial",
    unpaid: "Unpaid",
    no_cashflow_data: "No cashflow data available.",
    no_payment_status_data: "No payment status data available.",
    collection_rate_trend: "Collection Rate Trend",
    percent_rent_paid_monthly: "% of rent due that was paid monthly",
    no_collection_trend_data: "No collection trend data available.",
    occupancy_overview: "Occupancy Overview",
    active_leases_active_units: "Active leases / active units",
    no_occupancy_data: "No occupancy data available.",
    noi_trend_cash_basis: "NOI Trend (Cash Basis)",
    cash_collected_minus_expenses_monthly: "cash_collected - cash_expenses monthly",
    no_noi_data: "No NOI data available.",
    psp_distribution: "PSP Distribution",
    payment_provider_usage_breakdown: "Payment provider usage breakdown",
    clickpesa_azampay_fee: "ClickPesa/AzamPay fee:",
    flat: "flat",
    selcom_fee: "Selcom fee:",
    tenant_convenience_fee: "Tenant convenience fee:",
    no_psp_data: "No PSP data available.",
    arrears_aging: "Arrears Aging",
    outstanding_balances_by_age: "Outstanding balances by age (FIFO allocated)",
    no_arrears_data: "No arrears data available.",
    occupancy_trend: "Occupancy Trend",
    monthly_occupancy_rate_performance: "Monthly occupancy rate performance",
    no_occupancy_trend_data: "No occupancy trend data available.",
    payment_reconciliation: "Payment Reconciliation",
    psp_webhooks_match_fifo_ledger: "PSP Webhooks > Match > FIFO > Ledger",
    auto: "auto",
    no_reconciliation_data: "No reconciliation data available.",
    efd_tax_compliance: "EFD Tax Compliance",
    electronic_fiscal_device_receipt_status: "Electronic Fiscal Device receipt status",
    no_efd_data: "No EFD data available.",
    collection_rate: "Collection Rate",
    rent_due: "TZS rent due",
    total_arrears: "Total Arrears",
    cash_flow_analysis: "Uchambuzi wa Mtiririko wa Fedha",
    revenue_vs_expenses_monthly: "Mapato dhidi ya Matumizi (Mwezi)",
    payment_status: "Hali ya Malipo",
    distribution_of_payment_timeliness: "Usambazaji wa wakati wa malipo",
    on_time: "Kwa Wakati",
    late: "Imekawia",
    partial: "Sehemu",
    unpaid: "Haijalipwa",
    no_cashflow_data: "Hakuna data ya mtiririko wa fedha.",
    no_payment_status_data: "Hakuna data ya hali ya malipo.",
    collection_rate_trend: "Mwelekeo wa Kiwango cha Ukusanyaji",
    percent_rent_paid_monthly: "% ya kodi iliyolipwa kila mwezi",
    no_collection_trend_data: "Hakuna data ya mwelekeo wa ukusanyaji.",
    occupancy_overview: "Muhtasari wa Ujazaji",
    active_leases_active_units: "Mikataba hai / vitengo hai",
    no_occupancy_data: "Hakuna data ya ujazaji.",
    noi_trend_cash_basis: "Mwelekeo wa NOI (Msingi wa Fedha)",
    cash_collected_minus_expenses_monthly: "fedha zilizokusanywa - matumizi ya fedha (mwezi)",
    no_noi_data: "Hakuna data ya NOI.",
    psp_distribution: "Usambazaji wa PSP",
    payment_provider_usage_breakdown: "Uchanganuzi wa matumizi ya watoa huduma wa malipo",
    clickpesa_azampay_fee: "Ada ya ClickPesa/AzamPay:",
    flat: "moja kwa moja",
    selcom_fee: "Ada ya Selcom:",
    tenant_convenience_fee: "Ada ya urahisi wa mpangaji:",
    no_psp_data: "Hakuna data ya PSP.",
    arrears_aging: "Umri wa Madeni",
    outstanding_balances_by_age: "Salio linalodaiwa kwa umri (FIFO)",
    no_arrears_data: "Hakuna data ya madeni.",
    occupancy_trend: "Mwelekeo wa Ujazaji",
    monthly_occupancy_rate_performance: "Utendaji wa kiwango cha ujazaji kila mwezi",
    no_occupancy_trend_data: "Hakuna data ya mwelekeo wa ujazaji.",
    payment_reconciliation: "Upatanisho wa Malipo",
    psp_webhooks_match_fifo_ledger: "PSP Webhooks > Mechi > FIFO > Ledger",
    auto: "otomatiki",
    no_reconciliation_data: "Hakuna data ya upatanisho.",
    efd_tax_compliance: "Uzingatiaji wa Ushuru wa EFD",
    electronic_fiscal_device_receipt_status: "Hali ya risiti ya EFD",
    no_efd_data: "Hakuna data ya EFD.",
    outstanding_balances: "outstanding balances",
    occupancy_rate: "Occupancy Rate",
    of_units: "of",
    units: "units",
    net_operating_income: "Net Operating Income",
    cash_basis_noi: "cash basis NOI",
    monthly_expense_stat: "This Month's Total Expenses",
    financial_dashboard_title: "Financial Dashboard",
    financial_dashboard_subtitle: "Real-time overview of your property portfolio finances",
    collection_rate: "Kiwango cha Ukusanyaji",
    rent_due: "TZS kodi inayodaiwa",
    total_arrears: "Jumla ya Madeni",
    outstanding_balances: "salio linalodaiwa",
    occupancy_rate: "Kiwango cha Ujazaji",
    of_units: "ya",
    units: "vitengo",
    net_operating_income: "Mapato Halisi ya Uendeshaji",
    cash_basis_noi: "NOI ya msingi wa fedha",
    last_7_days: "Last 7 Days",
    last_30_days: "Last 30 Days",
    last_90_days: "Last 90 Days",
    last_12_months: "Last 12 Months",
    active_tenants: "Active Tenants",
    cash_collected: "Cash Collected",
    total_expenses: "Total Expenses",
    phone_placeholder: "+255 XXX XXX XXX",
    enter_nida_number: "Weka nambari ya NIDA",
    select_property: "Chagua mali",
    monthly_expense_stat: "Jumla ya Matumizi ya Mwezi Huu",
    financial_dashboard_title: "Dashibodi ya Fedha",
    financial_dashboard_subtitle: "Muhtasari wa kifedha wa mali zako kwa wakati halisi",
    last_7_days: "Siku 7 zilizopita",
    last_30_days: "Siku 30 zilizopita",
    last_90_days: "Siku 90 zilizopita",
    last_12_months: "Miezi 12 iliyopita",
    active_tenants: "Wapangaji Hai",
    cash_collected: "Fedha Zilizokusanywa",
    total_expenses: "Jumla ya Matumizi",
    generate_otp_for_tenant: "Tengeneza OTP kwa mpangaji",
    generated: "Imetengenezwa",
    generate: "Tengeneza",
    otp_sent_info: "OTP hii itatumwa kwa mpangaji kwa ajili ya kuanzisha akaunti",
    adding: "Inaongeza...",
    draft: "Rasimu",
    lease_end: "Mwisho wa Mkataba",
    status: "Hali",
    registered: "Imesajiliwa",
    time_remaining: "Muda Uliobaki",
    lease_expired: "Mkataba umeisha",
    days_left: "siku zimebaki",
    percent: "%%",
    call: "Piga Simu",
    view_profile: "Tazama Wasifu",
    monthly_payment_info: "Kiasi hiki kitatumika kama malipo ya mwezi kwa mpangaji",
    lease_start: "Tarehe ya Kuanza Mkataba",
    lease_period: "Kipindi cha Mkataba (miezi)",
    select_period: "Chagua kipindi",
    months: "miezi",
    total_tenants: "Jumla ya Wapangaji",
    active_leases: "Mikataba Hai",
    paid_this_month: "Imelipwa Mwezi Huu",
    overdue: "Imekawia",
    total: "Jumla",
    approval_rate: "Kiwango cha Uidhinishaji",
    avg_response: "Majibu wastani",
    approve: "Idhinisha",
    reject: "Kataa",
    send_lease: "Tuma Mkataba",
    review: "Kagua",
    details: "Maelezo",
    not_available: "Haipatikani",
    shared: "Imeshirikiwa",
    not_shared: "Haijashirikiwa",
    generate_lease_agreement: "Tengeneza Mkataba wa Kukodisha",
    error_move_to_review: "Tatizo kuhamisha kwenye ukaguzi. Tafadhali jaribu tena.",
    rejection_reason: "Sababu ya Kukataliwa",
                        tenant_applications_title: "Maombi ya Wapangaji",
                        review_and_manage_rental_applications: "Kagua na simamia maombi ya upangaji",
                        search_applications_placeholder: "Tafuta kwa jina, mali au barua pepe...",
                        pending: "Inasubiri",
                        in_review: "Inakaguliwa",
                        approved: "Imeidhinishwa",
                        rejected: "Imekataliwa",
                      rented: "Imepangishwa",
                    properties_title: "Mali",
                  manage_your_property_portfolio: "Simamia mali zako",
                  search_properties_placeholder: "Tafuta mali...",
                  avg_rent: "Kodi wastani",
                  no_properties_yet: "Hakuna mali bado",
                  add_first_property_to_get_started: "Ongeza mali yako ya kwanza kuanza",
                  bed: "chumba",
                  bath: "bafu",
                add_new_property: "Ongeza Mali Mpya",
                list_a_new_property_for_rent: "Orodhesha mali mpya ya kupangisha",
                basic_information: "Taarifa za Msingi",
                provide_main_details_about_property: "Toa maelezo muhimu kuhusu mali yako",
                property_title: "Kichwa cha Mali",
                eg_modern_downtown_apartment: "mf. Ghorofa ya Kisasa Mjini",
                describe_your_property: "Elezea mali yako...",
                location: "Mahali",
                where_is_your_property_located: "Mali yako iko wapi?",
                street_address: "Anwani ya Mtaa",
                eg_123_main_street: "123 Mtaa Mkuu",
                city: "Jiji",
                select_city: "Chagua jiji",
                region: "Eneo",
                eg_kinondoni: "mf. Kinondoni",
                postal_code: "Nambari ya Posta",
                optional: "Hiari",
                property_details: "Maelezo ya Mali",
                specifications_and_features: "Vipimo na sifa",
                eg_2: "2",
                eg_1200: "1200",
                public_toilet_available: "Choo cha Umma Kinapatikana",
                electricity_bill_type: "Aina ya Bili ya Umeme",
                select_type: "Chagua aina",
                individual_meter: "Kipimo Binafsi",
                shared_main_meter: "Kipimo Kikuu cha Pamoja",
                electricity_bill_amount: "Kiasi cha Bili ya Umeme (Tsh/mwezi)",
                eg_30000: "mf. 30000",
                water_bill_amount: "Kiasi cha Bili ya Maji (Tsh/mwezi)",
                eg_20000: "mf. 20000",
                submeters_installed: "Vipimo Vidogo Vimewekwa",
                monthly_rent: "Kodi ya Mwezi",
                eg_500000: "500000",
                security_deposit: "Amana ya Usalama",
                amenities: "Huduma",
                select_all_that_apply: "Chagua zote zinazofaa",
                photos: "Picha",
                add_photos_of_your_property: "Ongeza picha za mali yako",
                upload_photos: "Pakia Picha",
                cancel: "Ghairi",
                parking: "Maegesho",
                gym: "Gym",
                pool: "Bwawa la Kuogelea",
                dishwasher: "Mashine ya Kuosha Vyombo",
                ac: "AC",
                heating: "Joto",
                pet_friendly: "Rafiki wa Wanyama",
                balcony: "Balcony",
                yard: "Uwanja",
                furnished: "Imewekewa Vitu",
                utilities_included: "Huduma Zimejumuishwa",
              no_upcoming_payments: "Hakuna malipo yanayokuja",
            show_less: "Onyesha Chache",
          recent_applications: "Maombi ya Hivi Karibuni",
          new_tenant_applications_waiting_for_review: "Maombi mapya ya wapangaji yanayosubiri ukaguzi",
          upcoming_payments: "Malipo Yanayokuja",
          rent_payments_due_soon: "Malipo ya kodi yanayokaribia",
          view_all: "Tazama Zote",
        monthly_revenue: "Mapato ya Mwezi",
        compared_to_last_month: "Ikilinganishwa na mwezi uliopita",
        pending_applications: "Maombi Yanayosubiri",
        require_your_review: "Yanahitaji ukaguzi wako",
      reports: "Ripoti",
      lease_contract_template: "Mkataba wa Kukodisha",
      manage_lease_template_for_tenants: "Simamia mkataba wa kukodisha kwa wapangaji",
      open: "Fungua",
    applications: "Maombi",
    finance: "Fedha",
    expenses: "Matumizi",
    vaults: "Hazina",
    payments: "Malipo",
    send_lease: "Tuma Mkataba",
    property_occupied: "Mali Imejazwa",
    property_occupied_desc: "Mali hii tayari imepangishwa/imejazwa.\nHuwezi kupanga mali hii.",
    close: "Funga",
    manage_tenants: "Simamia wapangaji wako",
    add_tenant: "Ongeza Mpangaji",
    add_new_tenant: "Ongeza Mpangaji Mpya",
    first_name: "Jina la Kwanza",
    last_name: "Jina la Mwisho",
    dashboard: "Dashibodi",
    property_management: "Usimamizi wa Mali",
    verify_account: "Thibitisha Akaunti",
    verifying_account_tooltip: "Kuthibitisha akaunti yako kunaongeza uaminifu na kufungua vipengele vyote.",
    notifications: "Arifa",
    new: "mpya",
    no_notifications_yet: "Hakuna arifa bado",
    welcome_back_dashboard: "Karibu tena",
    dashboard_subtitle: "Hivi ndivyo mambo yalivyo kwa mali zako leo.",
    total_properties: "Jumla ya Mali",
    across_all_locations: "Katika maeneo yote",
    healthy: "Imara",
    moderate: "Wastani",
    low: "Chini",
    occupancy_rate: "Kiwango cha Ujazaji",
    welcome_back: "Karibu Tena",
    sign_in_to_continue: "Ingia kwenye akaunti yako kuendelea",
    sign_in: "Ingia",
    sign_up: "Jisajili",
    signing_in: "Inaingia...",
    enter_email_password: "Weka barua pepe na nenosiri kufikia dashibodi yako",
    email_placeholder: "wewe@mfano.com",
    password_placeholder: "••••••••",
    forgot_password: "Umesahau nenosiri?",
    dont_have_account: "Huna akaunti?",
    for_every_role: "Kwa Kila Wajibu",
    built_for_everyone: "Imetengenezwa kwa Kila Mtu katika Sekta ya Mali",
    three_powerful_dashboards: "Dashibodi tatu zenye nguvu zilizobinafsishwa kwa mahitaji yako",
    landlords_desc: "Orodhesha mali, chunguza wapangaji kwa ukaguzi wa mikopo, simamia mikataba, na kusanya malipo yote kwenye jukwaa moja.",
    property_portfolio_management: "Usimamizi wa mali nyingi",
    automated_tenant_screening: "Uchunguzi wa wapangaji otomatiki",
    rent_collection_tracking: "Ukusanyaji na ufuatiliaji wa kodi",
    tenants_desc: "Tafuta mali, tengeneza wasifu wako wa upangaji na taarifa zilizothibitishwa, omba papo hapo, na fanya malipo mtandaoni.",
    advanced_property_search: "Utafutaji wa mali wa hali ya juu",
    financial_profile_builder: "Jenzi wa wasifu wa kifedha",
    one_click_applications: "Maombi kwa bonyeza moja",
    agents_desc: "Simamia wateja, rahisisha mikataba, fuatilia tume, na pata taarifa za wapangaji zilizothibitishwa kwa kufunga mikataba haraka.",
    deal_pipeline_management: "Usimamizi wa mikataba",
    commission_tracking: "Ufuatiliaji wa tume",
    client_verification_tools: "Zana za uthibitishaji wa wateja",
    learn_more: "Jifunze zaidi",
    core_features: "Vipengele Muhimu",
    powerful_financial_verification: "Uthibitishaji wa Kifedha Yenye Nguvu",
    everything_you_need: "Kila kitu unachohitaji kufanya maamuzi salama ya upangaji",
    credit_score_integration: "Muunganiko wa Alama ya Mikopo",
    credit_score_integration_desc: "Ukaguzi wa alama ya mikopo papo hapo kutoka taasisi kuu. Tazama historia ya mikopo na mienendo ya malipo.",
    document_verification: "Uthibitishaji wa Nyaraka",
    document_verification_desc: "Pakia na thibitisha stakabadhi za malipo, taarifa za benki, na barua za ajira kwa usalama na AI.",
    background_checks: "Ukaguzi wa Historia",
    background_checks_desc: "Ukaguzi kamili wa historia ikiwa ni pamoja na rekodi za uhalifu, kufukuzwa, na historia ya upangaji.",
    income_verification: "Uthibitishaji wa Mapato",
    income_verification_desc: "Uthibitishaji wa mapato otomatiki kupitia mishahara na uchambuzi wa taarifa za benki.",
    property_analytics: "Takwimu za Mali",
    property_analytics_desc: "Uchambuzi wa soko, mapendekezo ya bei ya upangaji, na utabiri wa ujazaji kwa kutumia data ya soko la ndani.",
    api_for_lenders: "API kwa Wakopeshaji",
    api_for_lenders_desc: "API inayotoa taarifa za kifedha zilizothibitishwa kwa benki na taasisi za mikopo.",
    getting_started: "Kuanza",
    how_it_works: "Jinsi Inavyofanya Kazi",
    get_started_in_minutes: "Anza kwa dakika chache na mchakato wetu rahisi",
    create_your_profile: "Tengeneza Wasifu Wako",
    create_your_profile_desc: "Jisajili kama mmiliki, mpangaji, au wakala. Kamilisha wasifu wako na nyaraka za uthibitisho.",
    list_or_search_properties: "Orodhesha au Tafuta Mali",
    list_or_search_properties_desc: "Wamiliki wanaorodhesha mali na picha. Wapangaji wanatafuta na kuchuja kwa eneo, bei, na huduma. Mawakala wanasimamia pande zote.",
    verify_financial_information: "Thibitisha Taarifa za Kifedha",
    verify_financial_information_desc: "Wapangaji wanawasilisha maombi na ukaguzi wa mikopo na mapato otomatiki. Wamiliki wanakagua taarifa papo hapo.",
    close_the_deal: "Funga Mkataba",
    close_the_deal_desc: "Idhinisha maombi, saini mikataba kidijitali, na anza kukusanya kodi. Mawakala wanapata tume zinazofuatiliwa otomatiki.",
    simple_transparent_pricing: "Bei Rahisi na Wazi",
    choose_the_plan: "Chagua mpango unaokufaa. Boresha wakati wowote unavyokua.",
    free: "Bure",
    up_to_3_units: "Hadi vitengo 3",
    basic_property_management: "Usimamizi wa mali wa msingi",
    tenant_lease_tracking: "Ufuatiliaji wa wapangaji na mikataba",
    basic_reporting: "Ripoti za msingi",
    start_free: "Anza Bure",
    starter: "Starter",
    up_to_10_units: "Hadi vitengo 10",
    payments_reminders: "Malipo na vikumbusho",
    reports_arrears_tracking: "Ripoti na ufuatiliaji wa madeni",
    email_support: "Msaada wa barua pepe",
    start_starter: "Anza Starter",
    professional: "Professional",
    up_to_50_units: "Hadi vitengo 50",
    full_financial_dashboard_analytics: "Dashibodi kamili ya kifedha na uchambuzi",
    priority_support: "Msaada wa kipaumbele",
    advanced_exports: "Uhamishaji wa hali ya juu",
    start_professional: "Anza Professional",
    enterprise: "Enterprise",
    unlimited_units: "Vitengo visivyo na kikomo",
    api_access: "API ya ufikiaji",
    dedicated_support: "Msaada maalum",
    custom_integrations: "Muunganiko maalum",
    contact_sales: "Wasiliana na Mauzo",
    rentsecure: "RentSecure",
    footer_tagline: "Usimamizi kamili wa mali na uthibitishaji wa kifedha kwa soko la upangaji la kisasa.",
    product: "Bidhaa",
    api_documentation: "API Documentation",
    company: "Kampuni",
    about_us: "Kuhusu Sisi",
    contact: "Wasiliana",
    careers: "Ajira",
    legal: "Sheria",
    privacy_policy: "Sera ya Faragha",
    terms_of_service: "Masharti ya Huduma",
    security: "Usalama",
    all_rights_reserved: "Haki zote zimehifadhiwa.",
    clients: "Wateja",
    manage_landlord_tenant_relationships: "Simamia uhusiano wa wamiliki na wapangaji",
    add_client: "Ongeza Mteja",
    search_clients_placeholder: "Tafuta wateja...",
    filters: "Vichujio",
    total_clients: "Jumla ya Wateja",
    landlords: "Wamiliki",
    active: "Hai",
    credit_score: "Alama ya Mikopo",
    budget_range: "Kiwango cha Bajeti",
    active_deals: "Mikataba Hai",
    deals: "mkataba(i)",
    client_since: "Mteja Tangu",
    call: "Piga Simu",
    view_profile: "Tazama Wasifu",
    // Navigation
    dashboard: "Dashibodi",
    properties: "Mali",
    applications: "Maombi",
    tenants: "Wapangaji",
    payments: "Malipo",
    search: "Tafuta",
    favorites: "Vipendeleo",
    profile: "Wasifu",
    settings: "Mipangilio",
    clients: "Wateja",
    deals: "Mikataba",
    commissions: "Tume",
    logout: "Toka",

    // Home Page
    features: "Vipengele",
    how_it_works: "Jinsi Inavyofanya Kazi",
    pricing: "Bei",
    trusted_property_platform: "Jukwaa la Mali Linaloaminika",
    hero_title: "Usimamizi Kamili wa Mali na ",
    hero_title_highlight: "Uthibitishaji wa Kifedha",
    hero_subtitle: "Unganisha wamiliki, wapangaji, na mawakala kwa ukadiriaji wa mikopo papo hapo, uchunguzi wa wapangaji, na uthibitishaji salama wa kifedha. Fanya maamuzi sahihi haraka.",
    start_free_trial: "Anza Majaribio Bure",
    see_how_it_works: "Tazama Jinsi Inavyofanya Kazi",

    // Common
    welcome: "Karibu",
    back: "Rudi",
    login: "Ingia",
    register: "Jisajili",
    email: "Barua Pepe",
    password: "Nenosiri",
    confirmPassword: "Thibitisha Nenosiri",
    name: "Jina Kamili",
    phone: "Namba ya Simu",
    loading: "Inapakia",
    save: "Hifadhi",
    cancel: "Ghairi",
    edit: "Hariri",
    delete: "Futa",
    search_placeholder: "Tafuta...",
    filter: "Chuja",
    sort: "Panga",

    // Property
    property: "Mali",
    bedrooms: "Vyumba vya Kulala",
    bathrooms: "Vyumba vya Kuoga",
    squareFeet: "Futi za Mraba",
    rent: "Kodi",
    monthly_rent: "Kodi ya Mwezi",
    security_deposit: "Amana ya Usalama",
    available_date: "Tarehe Inapatikana",
    property_type: "Aina ya Mali",
    amenities: "Huduma",
    description: "Maelezo",
    location: "Mahali",
    view_details: "Tazama Maelezo",
    per_month: "kwa mwezi",
    arrears_aging_report: "Ripoti ya Umri wa Madeni",
    outstanding_balances_by_age_bucket: "Salio linalodaiwa kwa umri (FIFO)",
    total_outstanding: "Jumla ya Madeni",
    arrears_0_30_days: "Siku 0-30",
    arrears_31_60_days: "Siku 31-60",
    arrears_61_90_days: "Siku 61-90",
    arrears_90_plus_days: "Zaidi ya siku 90",
    amount_due: "Kiasi Kinachodaiwa",
    days_overdue: "Siku zilizokawia",
    remind: "Kumbusha",
    arrears_highest_risk_message: "Mary Kessy (siku 105 imekawia, 500K TZS) ni hatari zaidi kwa kuandikwa. Anzisha hatua rasmi. Ugawaji wa FIFO otomatiki unahakikisha madeni ya zamani yanapewa kipaumbele.",
    ledger_transactions: "Miamala ya Ledger",
    canonical_ledger_entries: "Kumbukumbu za ledger kutoka malipo ya PSP yaliyopatanishwa",
    entries: "rekodi",
    date: "Tarehe",
    psp: "PSP",
    method: "Njia",
    amount: "Kiasi",
    fee: "Ada",
    match: "Mechi",
    efd: "EFD",
    actions: "Vitendo",
    contact: "Wasiliana",
    property: "Mali",
    tenants: "wapangaji",

    // Status
    available: "Inapatikana",
    rented: "Imepangishwa",
    pending: "Inasubiri",
    approved: "Imeidhinishwa",
    rejected: "Imekataliwa",
    active: "Inafanya Kazi",
    inactive: "Haifanyi Kazi",
    completed: "Imekamilika",

    // Actions
    apply_now: "Omba Sasa",
    pay_now: "Lipa Sasa",
    view_property: "Tazama Mali",
    add_property: "Ongeza Mali",
    contact: "Wasiliana",

    // Pages
    landlord_dashboard: "Dashibodi ya Mmiliki",
    tenant_dashboard: "Dashibodi ya Mpangaji",
    agent_dashboard: "Dashibodi ya Wakala",
    property_flow_tanzania: "PROPERTY FLOW Tanzania",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
    const saved = localStorage.getItem("language") as Language | null
    if (saved && (saved === "en" || saved === "sw")) {
      setLanguage(saved)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (isClient) {
      localStorage.setItem("language", lang)
    }
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    return {
      language: "en" as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    }
  }
  return context
}
