const fs = require('fs');

const filePath = 'c:/PF/rental_platform.sql';
let text = fs.readFileSync(filePath, 'utf8');

// Basic MySQL -> Postgres syntax normalization.
text = text.replace(/\r\n/g, '\n');
text = text.replace(/`/g, '"');
text = text.replace(/\benum\s*\([^\)]*\)/gi, 'varchar(50)');
text = text.replace(/\btinyint\s*\(\s*1\s*\)/gi, 'smallint');
text = text.replace(/\bint\s*\(\s*\d+\s*\)/gi, 'integer');
text = text.replace(/\bdatetime\b/gi, 'timestamp without time zone');
text = text.replace(/\bcurrent_timestamp\s*\(\s*\)/gi, 'CURRENT_TIMESTAMP');
text = text.replace(/\s+ON UPDATE\s+current_timestamp\s*\(\s*\)/gi, '');
text = text.replace(/\s+ON UPDATE\s+CURRENT_TIMESTAMP/gi, '');
text = text.replace(/\)\s*ENGINE=InnoDB\s+DEFAULT\s+CHARSET=utf8mb4\s+COLLATE=utf8mb4_unicode_ci\s*;/gi, ');');
text = text.replace(/'0000-00-00'/g, 'NULL');

// Remove MySQL conditional comment directives if any remain.
text = text.replace(/^\/\*!.*\*\/;\s*$/gm, '');

// Convert MySQL ALTER TABLE index blocks into Postgres statements before generic parsing.
text = text.replace(
  /ALTER TABLE\s+"([^"]+)"\s+((?:\s*ADD\s+(?:PRIMARY\s+KEY|UNIQUE\s+KEY\s+"[^"]+"|KEY\s+"[^"]+")\s*\([^\)]+\)\s*,?\s*\n?)+);/gi,
  (_, table, body) => {
    const lines = body
      .split(/\n/)
      .map((s) => s.trim())
      .filter(Boolean)
      .map((s) => s.replace(/,$/, ''));

    const out = [];
    for (const line of lines) {
      let m = line.match(/^ADD\s+PRIMARY\s+KEY\s*\(([^\)]+)\)$/i);
      if (m) {
        out.push(`ALTER TABLE "${table}" ADD PRIMARY KEY (${m[1].trim()});`);
        continue;
      }

      m = line.match(/^ADD\s+UNIQUE\s+KEY\s+"([^"]+)"\s*\(([^\)]+)\)$/i);
      if (m) {
        const idxName = `${table}_${m[1]}`;
        out.push(`CREATE UNIQUE INDEX "${idxName}" ON "${table}" (${m[2].trim()});`);
        continue;
      }

      m = line.match(/^ADD\s+KEY\s+"([^"]+)"\s*\(([^\)]+)\)$/i);
      if (m) {
        const idxName = `${table}_${m[1]}`;
        out.push(`CREATE INDEX "${idxName}" ON "${table}" (${m[2].trim()});`);
      }
    }

    return out.join('\n');
  }
);

// Convert MySQL AUTO_INCREMENT ALTERs.
text = text.replace(
  /ALTER TABLE\s+"([^"]+)"\s+MODIFY\s+"([^"]+)"\s+integer\s+NOT\s+NULL\s+AUTO_INCREMENT\s*;/gi,
  'ALTER TABLE "$1" ALTER COLUMN "$2" ADD GENERATED BY DEFAULT AS IDENTITY;'
);

const statements = [];
let current = '';
for (const line of text.split('\n')) {
  current += line + '\n';
  if (line.trim().endsWith(';')) {
    statements.push(current.trim());
    current = '';
  }
}
if (current.trim()) statements.push(current.trim());

const out = [];
for (const stmt of statements) {
  const normalized = stmt.trim();

  // Convert MySQL index blocks to Postgres syntax.
  const alterMatch = normalized.match(/^ALTER TABLE\s+"([^"]+)"\s+([\s\S]+);$/i);
  if (alterMatch) {
    const table = alterMatch[1];
    const body = alterMatch[2];

    const hasIndexClauses = /ADD\s+KEY\s+|ADD\s+UNIQUE\s+KEY\s+|ADD\s+PRIMARY\s+KEY\s+/i.test(body);
    const hasConstraintClauses = /ADD\s+CONSTRAINT\s+/i.test(body);
    const hasModify = /\bMODIFY\b/i.test(body);

    if (hasModify) {
      // MySQL AUTO_INCREMENT -> Postgres identity
      const m = body.match(/MODIFY\s+"([^"]+)"\s+integer\s+NOT\s+NULL\s+AUTO_INCREMENT/i);
      if (m) {
        out.push(`ALTER TABLE "${table}" ALTER COLUMN "${m[1]}" ADD GENERATED BY DEFAULT AS IDENTITY;`);
        continue;
      }
    }

    if (hasIndexClauses && !hasConstraintClauses) {
      // Extract each clause and emit Postgres equivalents.
      const clauseRegex = /ADD\s+(PRIMARY\s+KEY|UNIQUE\s+KEY\s+"([^"]+)"|KEY\s+"([^"]+)")\s*\(([^\)]+)\)/gi;
      let match;
      while ((match = clauseRegex.exec(body)) !== null) {
        const kind = match[1].toUpperCase();
        const uniqName = match[2];
        const keyName = match[3];
        const cols = match[4].trim();

        if (kind === 'PRIMARY KEY') {
          out.push(`ALTER TABLE "${table}" ADD PRIMARY KEY (${cols});`);
        } else if (uniqName) {
          const idxName = `${table}_${uniqName}`;
          out.push(`CREATE UNIQUE INDEX "${idxName}" ON "${table}" (${cols});`);
        } else if (keyName) {
          const idxName = `${table}_${keyName}`;
          out.push(`CREATE INDEX "${idxName}" ON "${table}" (${cols});`);
        }
      }
      continue;
    }
  }

  out.push(normalized + (normalized.endsWith(';') ? '' : ';'));
}

let result = out.join('\n\n');

// Drop pure comment lines for cleaner execution.
result = result
  .split('\n')
  .filter((line) => !line.trim().startsWith('--'))
  .join('\n');

// Collapse excessive blank lines.
result = result.replace(/\n{3,}/g, '\n\n').trim() + '\n';

fs.writeFileSync(filePath, result, 'utf8');
console.log('Converted rental_platform.sql to PostgreSQL-compatible syntax (best-effort).');
